version: "3.8"
services:
  app:
    container_name: "app"
    build: .
    environment:
      - URL_MONGO=mongodb://mongo:27017/pokemon
    ports:
      - "8000:8000"
    expose:
      - "8000"
    links:
      - "database"
    depends_on:
      - "database"
    restart: on-failure

  database:
    container_name: "mongo"
    image: "mongo:latest"
    ports:
      - "27017:27017"
    restart: always

  database-seed:
    container_name: "mongo-seed"
    image: "mongo:latest"
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
    links:
      - "database"
    depends_on:
      - "database"
