version: "3.8"
services:
  app:
    container_name: "app-postgres"
    build: .
    environment:
      - PORT=8000
      - PGHOST=postgres
      - PGUSER=pokemon_admin
      - PGPASSWORD=12345
      - PGDATABASE=pokemon
      - PGPORT=5432
    ports:
      - "8000:8000"
    expose:
      - "8000"
    links:
      - "database"
    restart: always

  database:
    container_name: "postgres"
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=pokemon_admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=pokemon
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: always
